### ISSUE TITLE
Needs an icon

### ISSUE THREAD

**Issue by CleoMenezesJr** [CleoMenezesJr/getoverhere#1]
Well, I'm not good in design, so I expect someone's help to create something, especially for joining in the [GNOME Circle](https://circle.gnome.org/), in other words, that follow the GNOME HIG.

Any help will be appreciated! :)

**Comment by jimmac** [comment]
The two arrows signifying a message and response seem like a great metaphor. After a couple of iterations I think this would work well as an app icon, given some good color combination:

![Getoverhere_](https://user-images.githubusercontent.com/14821/191244277-7894b684-e579-4d90-831b-768710d8e769.png)

**Comment by CleoMenezesJr** [comment]
Coincidentally I had commented on a group that the only thing I imagine as an icon would be two arrows symbolizing the sending and receiving of the Requests' response. lmao

**Comment by thiagojack** [comment]
Hello! I used this colors, what do you think?
![icon](https://user-images.githubusercontent.com/5920212/191309536-fca3b75a-7f46-4316-bca9-4fbbac87a4eb.svg)

**Comment by CleoMenezesJr** [comment]
> I tried following the mockup as closely as possible. Not sure about the colors, though. Let me know what you think!
> 
> ![Screenshot from 2022-09-20 17-36-09](https://user-images.githubusercontent.com/77995380/191302605-73cacf60-9ea6-47d5-bf2c-df3937e11c39.png)
> ![arrows](https://user-images.githubusercontent.com/77995380/191303057-b8b794ae-5c79-4573-b354-c4f487b6b24e.svg)
> 
> 

Pretry nice. I just think the white color gives the icon a feeling of invisible among the other icons.

**Comment by jimmac** [comment]
With slightly over-the-top catchy colors in the PR above:

![image](https://user-images.githubusercontent.com/14821/191318858-88a532aa-4e4a-4e36-84bd-b1b5a82395b7.png)

**Comment by CleoMenezesJr** [comment]
Thanks to all for the contribution !!
